### PR TITLE
Upgrade to 23.11 as base

### PR DESCRIPTION
**Pull request by otavio**
Requires: #8

### CODE REVIEW

**Comment by otavio** [comment]
Once #8 is merged we can rebase this and merge. We got all packages merged into 23.11 so it removes a lot of local packages and code.

**Comment by otavio** [comment]
@katyo this is ready for review.

**Comment by katyo** [comment]
Oh seems you forget fix nixos channel in readme.

**Comment by otavio** [comment]
Sent #10.

**Pull request merged**
